replicaCount: 2

image:
  repository: antonzylyov/myapp:v2

ingress:
  host: bit.homework
  path: /bitapp/zylyov

service:
  type: NodePort
  port: 9000

mysql:
  fullnameOverride: mysqldb
  mysqlUser: zyzyzyz
  mysqlPassword: mypasswd
  mysqlDatabase: myapp
  service:
    port: 3306
